React calculator Math-Magicians
dasileker/react-calculator pull request #10
Opened 2021-05-24 14:28 UTC by dasileker

2021-05-25 15:25 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @dasileker, congratulations on this project :1st_place_medal: The PR is descriptive :+1: The README file is professional :slightly_smiling_face: The commit messages are easier to understand :100: Some of the test cases passed. However, kindly check the comments below and addressed them accordingly:

- Let us add a snapshot test for the following: this [link](https://jestjs.io/docs/snapshot-testing) could help
  - Home
  - Calculator
  - Quote
- Some of our tests are failing, kindly check below to see the files with the failing tests
  - Calculate.test.js, with a TypeError: result.toNumber is not a function and TypeError: big2.toNumber is not a function
  - Operate.test.js, TypeError: result.toNumber is not a function and TypeError: big2.toNumber is not a function
  - Index.test.js, expect(jest.fn()).toHaveBeenCalledWith(...expected)

[Optional]
- It would be professional if we have all our test in a Test directory

Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-05-25 15:30 UTC, addod19 requested changes

2021-05-25 15:30 UTC, addod19 commented on src/Components/App.js
> +// import NavBar from './Nav';
Kindly remove commented code

2021-05-25 15:30 UTC, addod19 commented on src/Components/Home.js
> +    </div> */}
Kindly remove commented piece of code

2021-05-25 15:30 UTC, addod19 commented on src/Components/Nav.js
> +// import Home from './Home';
Kindly remove commented piece of code

2021-05-26 11:32 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-05-29 10:08 UTC, merged